import React from 'react';
import Head from 'next/head';

interface HeadComponentProps {}

const HeadComponent: React.FC<HeadComponentProps> = () => {
  return (
    <Head>
        <title>Allume Consulting</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
    </Head>
  )
}

export default HeadComponent;
